---
title: "ID_measures"
output: ioslides_presentation
date: "2024-02-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
# Load libraries
library(data.table)
setDTthreads(11)
library(ggplot2)
library(stringr)
library(cowplot)
library(testit)
theme_set(theme_minimal()  +
            theme_cowplot(14, font_family = "Helvetica", rel_small = 0.8) + 
            theme(legend.position = "none",
                  strip.text = element_text(size = 9),
                  plot.margin = margin(1.5,2,1.5,2)))
library(brms)
library(gsubfn)
library(plotly)
source("utils.R")


savedModelsDir <- file.path("..", "saved_models")
cacheDir <- file.path("..", "saved_models", "ID_measures")
res <- 100 # Plotting resolution for lines
n_draws <- 300 # Subset of draws for prediction
rating_model <- "rmm1"

# Colors, lines labels
block_colors <- c("#cc1337", "#005b8d")
block_labels <- c("Coup-related", "General")
block_levels <- c("coup", "general")
block_lines <- c("solid", "dashed")

sum_ordinal <- function(pred) {
  pred_mult <- apply(pred, c(1, 2), function(x) sum((1:5) * x))
  pred_sum <- sum_draws(pred_mult)
}

plot_rating_ID <- function(model,
                                col,
                                label,
                                measures = c("coup_relevance_s", "coup_attitude_s", 
                                               "affect_s", "motivation_s"),
                                quadratic = c("coup_attitude_s")) {
  
  # Prepare values for prediction
  plot_dat <- rbindlist(lapply(unique(model$data$block),
                               function(x)
                                 data.table(col = plot_seq(model$data[col][model$data$block == x, ]),
                                            block = x)))
  
  colnames(plot_dat) <- c(col, "block")
  
  # Set all additional predictors to median
  plot_dat[, wait_s := 0]
  
  other_measures <- measures[measures != col]
  plot_dat[, (other_measures) := lapply(other_measures, function(x)
    median(model$data[x][[1]]))]
  
  if (!is.null(quadratic)) {
    lapply(quadratic, function(x) {
      plot_dat[, paste0("I(", x, ")^2") := .(get(x) ^ 2)]
    })
  }
  
  
  plot_pred <- function(resp,
                        resp_label){
    # Predict - this returns ndraws x npoints x 5
    pred <- fitted(
      model,
      newdata = plot_dat,
      re_formula = NA,
      summary = F,
      resp = resp
    )
    
    # Summarize into mean raiting
    pred <- sum_ordinal(pred)
    
    # Combine with predictors
    pred <- cbind(plot_dat, pred)
    
    # Prepare variables
    pred[, block := factor(block,
                           levels = block_levels,
                           labels = block_labels)]
    pred[, x := get(col)]
    
    
    p <- ggplot(pred, aes(
      x = x,
      y = m,
      fill = block,
      color = block
    )) +
      labs(
        x = label,
        y = resp_label,
        color = "Block",
        fill = "Block",
        linetype = "Block"
      ) +
      scale_x_continuous(expand = expansion(mult = c(0, 0))) +
      scale_fill_manual(breaks = block_labels,
                        values = block_colors) +
      scale_color_manual(breaks = block_labels,
                         values = block_colors) +
      scale_linetype_manual(breaks = block_labels,
                            values = block_lines) +
      theme(legend.position = "none")
    
    p <- getGeoms(p,
                  pred,
                  col = "block",
                  fill_legend = T)
    
    return(p)
    
  }
  
  p_affect <- plot_pred("affect",
                        "Expected answer affect")
  
  p_confidence <- plot_pred("confidence",
                        "Confidence")
  
  p_useful <- plot_pred("useful",
                        "Expected ansewr usefulness")

  
  # This might help with memory usage
  gc()
  
  return(list(p_useful, p_confidence, p_affect))
}

plot_rating_grid <- function(...){
  
  plots_list <- list(...)
    
  l <- get_legend(plots_list[[1]] + theme(
      legend.position = "top",
      legend.justification = "center"
  ))
  
  p <- plot_grid(
    l,
    plot_grid(
      plotlist = plots_list,
      nrow = 1
    ),
    ncol = 1,
    rel_heights = c(.1, 1)
  )
  
  return(p)
}

rmm1 <- brm(file = file.path(savedModelsDir, rating_model))

sampleName <- "v1.01"
source("load_data_and_exclude.R")
list[wait, rating_clps, know_test,
     prob_judge, quest, quality] = load_exclude(sampleName)

quest_text <- unique(wait[, .(questionId, question)])
quest_text[, question := gsub('""""', '"', question)]

set.seed(0)
```

```{r ID_rating_plotting}
# Make plots
list[p_coup_rel_useful, 
     p_coup_rel_confidence, 
     p_coup_rel_affect] <- plot_rating_ID(rmm1, "coup_relevance_s", 
                                          "Coup relevance (std.)")
list[p_coup_att_useful, 
     p_coup_att_confidence, 
     p_coup_att_affect] <- plot_rating_ID(rmm1, "coup_attitude_s", 
                                          "Coup attitude (std.)")

list[p_aff_useful, 
     p_aff_confidence, 
     p_aff_affect] <- plot_rating_ID(rmm1, "affect_s", "Mood (std.)")

list[p_mot_useful, 
     p_mot_confidence, 
     p_mot_affect] <- plot_rating_ID(rmm1, "motivation_s", 
                                          "Motivational activation\n(std.)")

# Set common y limits
list[p_coup_rel_useful,
     p_coup_att_useful,
     p_aff_useful,
     p_mot_useful] <-
  set_common_y_limits(p_coup_rel_useful,
                      p_coup_att_useful,
                      p_aff_useful,
                      p_mot_useful)

list[p_coup_rel_confidence,
     p_coup_att_confidence,
     p_aff_confidence,
     p_mot_confidence] <-
  set_common_y_limits(p_coup_rel_confidence,
                      p_coup_att_confidence,
                      p_aff_confidence,
                      p_mot_confidence)

list[p_coup_rel_affect,
     p_coup_att_affect,
     p_aff_affect,
     p_mot_affect] <-
  set_common_y_limits(p_coup_rel_affect,
                      p_coup_att_affect,
                      p_aff_affect,
                      p_mot_affect)
```

## Model
TK TK TK

`r as.character(rmm1$formula)[[1]]`

## Coup Relevance
```{r coup_relevance}
plot_rating_grid(p_coup_rel_useful,
                 p_coup_rel_confidence,
                 p_coup_rel_affect)
```

## Coup Attitude
```{r coup_attitude}
plot_rating_grid(p_coup_att_useful, 
     p_coup_att_confidence, 
     p_coup_att_affect
)
```

## Mood
```{r affect}
plot_rating_grid(p_aff_useful,
                 p_aff_confidence,
                 p_aff_affect)
```

## Motivational activation
```{r motivation}
plot_rating_grid(p_mot_useful,
                 p_mot_confidence,
                 p_mot_affect)
```